name: Push heroku

on:
  push:
    branches: ['main']
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
          repository: slow/nitro-sniper
          path: nitro-sniper

      - name: Generate random repo name
        run: |
          echo repoName=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 13 ; echo '') >> $GITHUB_ENV

      - name: Set up credentials
        run: |
          git config --global user.name 'eternal'
          git config --global user.email '73202350+slow@users.noreply.github.com'
          git config --global init.defaultBranch 'main'
          git config --global push.default 'current'


      - name: Clone repository & change button link
        run: |
          cd nitro-sniper
          sed -i -E 's!heroku-hate-club\/.[A-Za-z0-9]+!heroku-hate-club/${{ env.repoName }}!g' README.md
          git add .
          git commit -am 'Change heroku deploy url [skip ci]'
          git push

      - name: Delete files
        run: |
          cd nitro-sniper
          rm -rf .github
          rm -rf README.md
          rm -rf CHANGELOG.md
          rm -rf .git
          rm -rf .releaserc.json
          rm -rf .env
          cd ..

      - name: Delete other repos, commit changes & push
        run: |
          cd nitro-sniper
          echo ${{ secrets.GH_TOKEN }} >> token.txt
          gh auth login --with-token < token.txt
          gh repo list heroku-hate-club --json name --jq ".[] | .name" | while read -r line; do  gh api -X DELETE "repos/heroku-hate-club/$line"; done
          gh repo create heroku-hate-club/${{ env.repoName }} --public -y
          rm -rf ${{ env.repoName }}
          rm -rf token.txt
          git init
          git remote add origin https://heroku-hate-club:${{ secrets.GH_TOKEN }}@github.com/heroku-hate-club/${{ env.repoName }}
          git add .
          git commit -m "Release"
          git push --set-upstream --force origin main
